import { fontSans } from '@/lib/font';
import './globals.css';
import { Providers } from '@/components/providers';
import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-BR">
      <body className={fontSans.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
