name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress binary
        run: pnpm dlx cypress install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'
        env:
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
          NEXT_PUBLIC_MODE: ${{ secrets.NEXT_PUBLIC_MODE }}
